# Rebind prefix
unbind C-b
set -g prefix C-a

# ---------------------------------------------------------
# Vim-style Pane Navigation and Resizing
# ---------------------------------------------------------

# Switch panes with lowercase h, j, k, l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with uppercase H, J, K, L (Shift + letter)
# The -r flag makes it repeatable, so you can press Prefix once 
# and then hold/tap Shift + H/J/K/L multiple times.
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# Remap jump to previous pane (since we use l for right nav now
bind -r i last-pane 

# Make cycling tmux panes repeatable
bind -r o select-pane -t :.+
bind -r C-o rotate-window -t :.+

# use Ctrl + hjkl without prefix
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Allow vim style navigation on tmux copy mode
setw -g mode-keys vi
